This workflow is a simple Continuous Integration (CI) process.
It is triggered on every push to the main branch and every pull request.
name: Pima Diabetes Predictor CI

on:
push:
branches: [ "main", "master" ]
pull_request:
branches: [ "main", "master" ]

permissions:
contents: read

jobs:
build:
runs-on: ubuntu-latest

steps:
- uses: actions/checkout@v4
- name: Set up Python 3.10
  uses: actions/setup-python@v4
  with:
    python-version: "3.10"
    cache: 'pip'

- name: Install dependencies
  run: |
    python -m pip install --upgrade pip
    if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
- name: Run model training script
  # This step is crucial for ensuring that the model.py script can run without errors
  # and that it generates the model.pkl file.
  run: python model.py
  
- name: Run Flask app tests (optional, but good practice)
  # You can add more comprehensive tests here if you have them.
  run: |
    echo "Basic check: app.py can be run."
    python app.py &
    sleep 5
    kill %1

